apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qwen-serve
  template:
    metadata:
      labels:
        app: qwen-serve
    spec:
      containers:
      - name: vllm
        # Your image with the updated serve.sh
        image: zbirenbaum/qwen-serve-fa3:latest 
        # --- SECRETS INJECTION ---
        # This loads ALL vars from your .env file as environment variables
        envFrom:
        - secretRef:
            name: qwen-env
            
        # Manually set specific overrides if needed
        env:
        - name: VLLM_ATTENTION_BACKEND
          value: "FLASH_ATTN_V3"
        - name: NCCL_DEBUG
          value: "INFO"
        
        ports:
        - containerPort: 8000
        
        resources:
          limits:
            nvidia.com/gpu: 4
          requests:
            nvidia.com/gpu: 4
            cpu: 48
            memory: "400Gi"
            
        volumeMounts:
        - name: model-cache
          mountPath: /data
          
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: qwen-weights-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-entrypoint
spec:
  selector:
    app: qwen-serve
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
