apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lora-weights-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi # Sufficient for many LoRA checkpoints
  storageClassName: shared-vast-ord1
