apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen-weights-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi # 1TB for the Qwen 235B model
  storageClassName: shared-vast-ord1
